# Introduction to NumPy

**NumPy** (Numerical Python) is the foundational library for numerical computing in Python.  
It provides fast, memory-efficient arrays and a large collection of mathematical functions.

NumPy is used everywhere in data science, machine learning, and scientific computing — it powers libraries like pandas, scikit-learn, and TensorFlow under the hood.

## 1. Installation & Import

NumPy is included in most Python distributions (Anaconda, Google Colab, etc.).  
If you need to install it:

```
pip install numpy
```
```
conda install anaconda::numpy
```

By convention, NumPy is always imported as `np`:

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.6


## 2. Creating Arrays

The core object in NumPy is the **ndarray** (n-dimensional array).  
Unlike Python lists, all elements in a NumPy array must be the **same data type**, which makes operations much faster.

| Python List | NumPy Array |
|---|---|
| `[1, 2, 3]` | `np.array([1, 2, 3])` |
| Mixed types allowed | Single type only |
| Slow math | Fast vectorized math |

Use `np.array()` to create an numpy array from a Python list:

In [3]:
# 1D array
nums = np.array([1, 2, 3])
print("1D array:", nums)

# 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", matrix)

1D array: [1 2 3]
2D array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Comparing Python list vs NumPy array behaviour
# multiplication
# python list: repeats the list
my_list = [1, 2, 3]
my_list_doubled = my_list * 2 
print("List * 2:  ", my_list_doubled)

# NumPy array: multiplies each element
my_array = np.array([1, 2, 3])
my_array_doubled = my_array * 2
print("Array * 2: ", my_array_doubled)
print("Type:      ", type(my_array))

List * 2:   [1, 2, 3, 1, 2, 3]
Array * 2:  [2 4 6]
Type:       <class 'numpy.ndarray'>


In [5]:
# addition
# Python List: Appends the second list to the first
list_a = [1, 2, 3]
list_b = [4, 5, 6]
list_a_plus_b = list_a + list_b
print("List + List:  ", list_a_plus_b)

# NumPy Array: Performs vector addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_a_plus_b = array_a + array_b
print("Array + Array: ", array_a_plus_b)

List + List:   [1, 2, 3, 4, 5, 6]
Array + Array:  [5 7 9]


## 3. Array Properties — `ndim`, `shape`, `dtype`

Every NumPy array has three key properties:

| Property | Description | Example |
|---|---|---|
| `array.ndim` | Number of dimensions | `2` how many axes the array has |
| `array.shape` | Tuple of sizes per dimension | `(3, 4)` means 3 rows, 4 cols |
| `array.dtype` | Data type of the elements | `int64`, `float64`, `str` |

Shape conventions:
- **1D:** `(n,)` — a flat list of n elements
- **2D:** `(rows, columns)`
- **3D:** `(depth, rows, columns)`

In [6]:
# 0D — scalar (single value)
a0 = np.array(42)
print('np.array(42)')
print("0D scalar:", a0, "| ndim:", a0.ndim, "| shape:", a0.shape)

np.array(42)
0D scalar: 42 | ndim: 0 | shape: ()


In [7]:
# 1D array
a1 = np.array([1, 2, 3, 4])
print('np.array([1, 2, 3, 4])')
print("1D:", a1, "| ndim:", a1.ndim, "| shape:", a1.shape)

np.array([1, 2, 3, 4])
1D: [1 2 3 4] | ndim: 1 | shape: (4,)


In [8]:
# 2D array
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print('a2 = np.array([[1, 2, 3], [4, 5, 6]])')
print("2D:\n", a2, "\nndim:", a2.ndim, "| shape:", a2.shape)

a2 = np.array([[1, 2, 3], [4, 5, 6]])
2D:
 [[1 2 3]
 [4 5 6]] 
ndim: 2 | shape: (2, 3)


In [9]:
# 3D array
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])')
print("3D:\n", a3, "\nndim:", a3.ndim, "| shape:", a3.shape)

a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
ndim: 3 | shape: (2, 2, 2)


In [10]:
# dtype — data type of elements
int_array = np.array([1, 2, 3])
float_array = np.array([1.5, 2.5, 3.5])
str_array = np.array(['a', 'b', 'c'])

print("Integer array dtype:", int_array.dtype)
print("Float array dtype:  ", float_array.dtype)
print("String array dtype: ", str_array.dtype)

# You can specify dtype explicitly
forced_float = np.array([1, 2, 3], dtype=float)
print("Forced to float:    ", forced_float, "| dtype:", forced_float.dtype)

Integer array dtype: int64
Float array dtype:   float64
String array dtype:  <U1
Forced to float:     [1. 2. 3.] | dtype: float64


## 4. Array Creation Functions

Instead of converting lists manually, NumPy provides convenience functions to create common arrays:

| Function | Description |
|---|---|
| `np.zeros(shape)` | Array filled with 0s |
| `np.ones(shape)` | Array filled with 1s |
| `np.full(shape, val)` | Array filled with a given value |
| `np.arange(start, stop, step)` | Evenly spaced values (like `range()`) |
| `np.linspace(start, stop, n)` | n evenly spaced values between start and stop |
| `np.eye(n)` | n×n identity matrix |

In [11]:
print("zeros (2x3):\n", np.zeros((2, 3)))

zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print("ones (3x2):\n",  np.ones((3, 2)))

ones (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
print("full (2x2) with 7:\n", np.full((2, 2), 7))

full (2x2) with 7:
 [[7 7]
 [7 7]]


In [14]:
print("arange(0, 10, 2):", np.arange(0, 10, 2))

arange(0, 10, 2): [0 2 4 6 8]


In [15]:
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [16]:
print("identity (3x3):\n", np.eye(3))

identity (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 5. Indexing

NumPy supports two indexing styles:
- **Chain indexing:** `array[0][1][2]` — same as lists, but slower
- **Multi-dimensional indexing:** `array[0, 1, 2]` — preferred, faster

In [17]:
array = np.array([[['a', 'b'], ['c', 'd']],
                  [['e', 'f'], ['g', 'h']]])

# Chain indexing
print("Chain:  array[0][0][0] =", array[0][0][0])   # 'a'
print("Chain:  array[0][0][0] =", array[0][0][1])   # 'b'

# Multi-dimensional indexing
print("Multi:  array[0, 0, 0] =", array[0, 0, 0])   # 'a'
print("Multi:  array[0, 0, 1] =", array[0, 0, 1])   # 'b'

Chain:  array[0][0][0] = a
Chain:  array[0][0][0] = b
Multi:  array[0, 0, 0] = a
Multi:  array[0, 0, 1] = b


### Exercise — Spell "cat" with indexing

Using multi-dimensional indexing, extract the letters `c`, `a`, `t` from the array below and print the word.

In [18]:
array = np.array([[['a', 'b'], ['c', 'd']],
                  [['e', 'f'], ['g', 'h']],
                  [['i', 'j'], ['k', 'l']],
                  [['m', 'n'], ['o', 'p']],
                  [['q', 'r'], ['s', 't']],
                  [['u', 'v'], ['w', 'x']],
                  [['y', 'z'], ['a', 'b']]])

# [depth - 7, height - 2, width - 2]
# Hint: 'a' is at [0, 0, 0], 't' is at [4, 1, 1]


## 6. Slicing

Slicing syntax: `array[start:stop:step]`  
For 2D arrays: `array[row_slice, col_slice]`

- Omitting `start` defaults to the beginning
- Omitting `stop` defaults to the end
- `:` alone means "all"

In [19]:
array = np.array([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12],
                  [13, 14, 15, 16]])

# Row slicing
print("Row 1: ", array[1])
print("Rows 2 onward:\n", array[2:])
print("First 2 rows:\n", array[:2])
print("Every 2nd row:\n", array[::2])
print("Reversed rows:\n", array[::-1])

Row 1:  [5 6 7 8]
Rows 2 onward:
 [[ 9 10 11 12]
 [13 14 15 16]]
First 2 rows:
 [[1 2 3 4]
 [5 6 7 8]]
Every 2nd row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Reversed rows:
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [20]:
# Column slicing — use [:, col_slice] to select all rows
print("Column 0: ",  array[:, 0])
print("Last 2 columns:\n",     array[:, 2:])
print("First 2 columns:\n",    array[:, :2])
print("Every 2nd column:\n",   array[:, ::2])
print("Columns 1-2:\n",        array[:, 1:3])

Column 0:  [ 1  5  9 13]
Last 2 columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
First 2 columns:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Every 2nd column:
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
Columns 1-2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [21]:
# Slicing both rows and columns
print("Top-left 2x2:\n",     array[0:2, 0:2])
print("Top-right 2x2:\n",    array[0:2, 2:4])
print("Bottom-left 2x2:\n",  array[2:4, 0:2])
print("Bottom-right 2x2:\n", array[2:4, 2:4])

Top-left 2x2:
 [[1 2]
 [5 6]]
Top-right 2x2:
 [[3 4]
 [7 8]]
Bottom-left 2x2:
 [[ 9 10]
 [13 14]]
Bottom-right 2x2:
 [[11 12]
 [15 16]]


### Exercise: slicing

In [22]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

1. Slice the array to get the elements [40, 50, 60, 70].

2. Get the first 5 elements ([10, 20, 30, 40, 50]) without typing the 0 for the start index.

3. Get every second element from the entire array ([10, 30, 50, 70, 90]).

4. Reverse the entire array using a negative step size ([100, 90, 80, ...]).

## 7. Reshaping Arrays

You can change an array's shape without changing its data using `reshape()`.  
The total number of elements must stay the same.

- `reshape(rows, cols)` — change dimensions
- `flatten()` — collapse to 1D
- `T` — transpose (swap rows and columns)

In [23]:
original = np.arange(1, 13)          # [1, 2, ..., 12]
print("Original (1D):", original)

reshaped = original.reshape(3, 4)    # 3 rows, 4 columns
print("Reshaped to (3, 4):\n", reshaped)

reshaped_3d = original.reshape(2, 2, 3)  # 3D
print("Reshaped to (2, 2, 3):\n", reshaped_3d)

flat = reshaped.flatten()            # back to 1D
print("Flattened:", flat)

print("Transposed:\n", reshaped.T)   # swap rows & columns

Original (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to (2, 2, 3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transposed:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 8. Arithmetic

NumPy arithmetic is **element-wise** — operations apply to every element automatically (no loops needed).

### Scalar arithmetic
Apply a single value to every element:

In [24]:
array = np.array([1, 2, 3])
print("Original:  ", array)
print("+ 1:       ", array + 1)
print("- 2:       ", array - 2)
print("* 3:       ", array * 3)
print("/ 4:       ", array / 4)
print("** 2:      ", array ** 2)

Original:   [1 2 3]
+ 1:        [2 3 4]
- 2:        [-1  0  1]
* 3:        [3 6 9]
/ 4:        [0.25 0.5  0.75]
** 2:       [1 4 9]


### Vectorized math functions

NumPy has built-in math functions that apply to entire arrays at once:

In [25]:
array = np.array([1.5, 2.3, 3.6])
print("sqrt: ", np.sqrt(array))
print("floor:", np.floor(array))
print("round:", np.round(array))
print("log:  ", np.log(array))
print("pi =  ", np.pi)

sqrt:  [1.22474487 1.51657509 1.8973666 ]
floor: [1. 2. 3.]
round: [2. 2. 4.]
log:   [0.40546511 0.83290912 1.28093385]
pi =   3.141592653589793


### Element-wise arithmetic between arrays

When two arrays have the same shape, operations apply element-by-element:

In [26]:
array1 = np.array([1, 2, 4])
array2 = np.array([4, 5, 6])
print("array1:      ", array1)
print("array2:      ", array2)
print("array1 + array2:", array1 + array2)
print("array1 - array2:", array1 - array2)
print("array1 * array2:", array1 * array2)
print("array1 / array2:", array1 / array2)
print("array1 ** array2:", array1 ** array2)

array1:       [1 2 4]
array2:       [4 5 6]
array1 + array2: [ 5  7 10]
array1 - array2: [-3 -3 -2]
array1 * array2: [ 4 10 24]
array1 / array2: [0.25       0.4        0.66666667]
array1 ** array2: [   1   32 4096]


### Exercise on Arithmetic

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

1. Multiply every element in array a by 5.

2. Add array a and array b together.

3. Divide array b by array a.

## 9. Comparisons & Filtering

### Comparisons

Comparison operators return a **boolean array** of the same shape:

In [42]:
scores = np.array([91, 55, 100, 73, 82, 64])
print("scores:       ", scores)
print("== 100:       ", scores == 100)
print(">= 60:        ", scores >= 60)
print("< 90:         ", scores < 90)

scores:        [ 91  55 100  73  82  64]
== 100:        [False False  True False False False]
>= 60:         [ True False  True  True  True  True]
< 90:          [False  True False  True  True  True]


### Boolean Filtering

Use a boolean array as an index to **select** elements that meet a condition.  
Combine conditions with `&` (and) and `|` (or) — always wrap each condition in parentheses.

In [48]:
# Simple filtering
print("Scores below 60:", scores[scores < 60])

# Modify in place — set failing scores to 0
scores[scores < 70] = 0
print("After zeroing failures:", scores)

Scores below 60: [55]
After zeroing failures: [ 91   0 100  73  82   0]


In [47]:
scores = np.array([91, 55, 100, 73, 82, 64])
# can also write it
mask = scores < 70
scores[mask]

array([55, 64])

In [29]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
print("Under 18:     ", teenagers)

adults = ages[(ages >= 18) & (ages < 65)]
print("Adults 18-64: ", adults)

evens = ages[ages % 2 == 0]
print("Even ages:    ", evens)

Under 18:      [17 16 15]
Adults 18-64:  [21 19 20 30 18 39 22 18 19 20 21]
Even ages:     [20 16 30 18 22 18 20]


### `np.where()` — conditional replacement

`np.where(condition, value_if_true, value_if_false)` keeps the array shape and replaces non-matching elements:

In [30]:
# Keep adult ages as-is; replace minors with 0
adults_grid = np.where(ages >= 18, ages, 0)
print("Adults only (0 for minors):\n", adults_grid)

Adults only (0 for minors):
 [[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


### Exercise Comparison & Filtering

In [40]:
temps = np.array([18, 22, 35, 12, 40, 25, 31, 15])

1. Create a boolean mask that checks which temperatures are strictly greater than 25. 
2. Use the mask from Exercise 1 to filter temps so you only get the actual temperatures that are greater than 25.
3. A freezing front comes in! Find all temperatures below 15 and set them exactly to 0.

## 10. Broadcasting

**Broadcasting** lets NumPy perform operations on arrays with **different shapes** by automatically "stretching" the smaller array to match the larger one — without actually copying data.

Broadcasting rules:
- Dimensions are compared from the right
- Two dimensions are compatible if they are **equal** or one of them is **1**

```
Shape (1, 4)  →  broadcast →  (4, 4)
Shape (4, 1)  →  broadcast →  (4, 4)
```

In [31]:
array1 = np.array([[1, 2, 3, 4]])     # shape (1, 4) — row vector
array2 = np.array([[1], [2], [3], [4]])  # shape (4, 1) — column vector

print("array1 shape:", array1.shape)
print("array2 shape:", array2.shape)

array1 shape: (1, 4)
array2 shape: (4, 1)


In [32]:
# Broadcasting produces a (4, 4) outer-product matrix
print("array1 * array2 (broadcasted to 4x4):\n", array1 * array2)

array1 * array2 (broadcasted to 4x4):
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


## 11. Aggregate Functions

Aggregate functions reduce an array to a single value (or values along an axis).

| Function | Description |
|---|---|
| `np.sum()` | Sum of elements |
| `np.mean()` | Average |
| `np.std()` | Standard deviation |
| `np.var()` | Variance |
| `np.min()` / `np.max()` | Minimum / Maximum |
| `np.argmin()` / `np.argmax()` | Index of min / max |

Use `axis=0` to aggregate **down columns**, `axis=1` to aggregate **across rows**.

In [33]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])
print("Array:\n", array)
print("---")
print("Sum:    ", np.sum(array))
print("Mean:   ", np.mean(array))
print("Std:    ", np.std(array))
print("Var:    ", np.var(array))
print("Min:    ", np.min(array))
print("Max:    ", np.max(array))
print("Argmin: ", np.argmin(array), "(flat index)")
print("Argmax: ", np.argmax(array), "(flat index)")

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---
Sum:     55
Mean:    5.5
Std:     2.8722813232690143
Var:     8.25
Min:     1
Max:     10
Argmin:  0 (flat index)
Argmax:  9 (flat index)


In [34]:
# axis=0 → collapse rows (sum each column)
print("Sum per column (axis=0):", np.sum(array, axis=0))

# axis=1 → collapse columns (sum each row)
print("Sum per row    (axis=1):", np.sum(array, axis=1))

# Works for other aggregates too
print("Max per column (axis=0):", np.max(array, axis=0))
print("Mean per row   (axis=1):", np.mean(array, axis=1))

Sum per column (axis=0): [ 7  9 11 13 15]
Sum per row    (axis=1): [15 40]
Max per column (axis=0): [ 6  7  8  9 10]
Mean per row   (axis=1): [3. 8.]


### Exercise

In [50]:
# the steps a person took everyday for a week
steps = np.array([7500, 10200, 4300, 12500, 8900, 9100, 11000])

1. Find the total number of steps walked over the entire week, and the average daily step count.
2. Find the highest step count recorded.
3. Use np.argmax() to find the index of the day with the highest step count. Which day of the week is that, assuming index 0 is Monday?

## 12. Random Numbers

NumPy's random module is essential for simulations, data generation, and machine learning.

**Older approach:** use `np.random.seed()`<br>
**Recommended approach:** use `np.random.default_rng()` 
Set a **seed** to get reproducible results.

recommended approach

In [35]:
# Without seed — different result each run
rng = np.random.default_rng() # create a random number generator object
print("Random integers (1-6):", rng.integers(low=1, high=7, size=3))

Random integers (1-6): [4 6 3]


older approach

In [36]:
# With seed — same result every run (useful for reproducibility)
rng = np.random.default_rng(seed=42)
print("Seeded integers (1-6):", rng.integers(low=1, high=7, size=3))

Seeded integers (1-6): [1 5 4]


In [37]:
rng = np.random.default_rng(seed=42)

# Uniform — any float between 0 and 1
# random() returns a single float
print("Single uniform:", rng.random())
print("Single uniform:", rng.random(size=5))  # 5 random floats in [0, 1)

# Uniform between -1 and 1, shaped (3, 2)
# uniform(low=lower_bound, high=upper_bound, size=shape)
print("Uniform (-1, 1) matrix:\n", rng.uniform(low=-1, high=1, size=(3, 2)))

# Normal distribution (bell curve)
# normal(loc=mean, scale=stddev, size=shape)
print("Normal (mean=0, std=1):", rng.normal(loc=0, scale=1, size=5))

Single uniform: 0.7739560485559633
Single uniform: [0.43887844 0.85859792 0.69736803 0.09417735 0.97562235]
Uniform (-1, 1) matrix:
 [[ 0.5222794   0.57212861]
 [-0.74377273 -0.09922812]
 [-0.25840395  0.85352998]]
Normal (mean=0, std=1): [ 0.0660307   1.12724121  0.46750934 -0.85929246  0.36875078]


In [38]:
rng = np.random.default_rng(seed=42)

# Shuffle an array in place
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print("Shuffled:", array)

# Random choice from an array
fruits = np.array(["apple", "orange", "banana"])
print("One fruit:", rng.choice(fruits))
print("Three fruits (with replacement):", rng.choice(fruits, size=3))

Shuffled: [5 3 4 2 1]
One fruit: orange
Three fruits (with replacement): ['banana' 'apple' 'banana']


### Exercise

In [52]:
rng = np.random.default_rng(seed=42)
contestants = np.array(["Alice", "Bob", "Charlie", "David", "Eva", "Frank"]) # for question 2

1. Use your rng to simulate rolling a standard 6-sided die 10 times. (use rng.integers())
2. Given a list of names, randomly select 3 unique winners without replacement (the same person can't win twice).

### Useful reference:
* [The Python NumPY module](https://numpy.org/doc/stable/reference/routines.html) - contains a list of numpy commands